### ISSUE TITLE
Error in jobManagementSystem docker logs

### ISSUE THREAD

**Issue by notxt** [gt-health/PACER#19]
Running into the following error in `jobManagementSystem` when I `docker logs -f [container id]`:
```
Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2020-08-12 17:08:33.885 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaAutoConfiguration.class]: Invocation of init method failed; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1628) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:555) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1078) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:857) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.10.RELEASE.jar:4.3.10.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) ~[spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
...
```

Not sure if it's an infrastructure issue on my end or a bug 🤔 

The service is returning 404s when I try to POST, but I'd originally thought that was an issue with my POST body. Any thoughts?

thanks
michael

( fyi @MikeRileyGTRI )

**Comment by MikeRileyGTRI** [comment]
I believe this is an error with allowing the "latest" on maven build containers, while java runtime no longer support jaxb anymore post JDK10. I'll try finding a version of the maven builder that is correct for this, probably jdk-10.

**Comment by notxt** [comment]
merci beacoup @MikeRileyGTRI ! Thanks for the response!

lemme know if there's anything I can do to help

**Comment by MikeRileyGTRI** [comment]
I've been able to replicate the issue, and created a fix! Tomcat docker instances moved out of jdk-8 compatibility, so I've clamped the tomcat container versions down. I've pushed the fix into master and created a new tag instance for you: 1.5.3 https://github.com/gt-health/PACER/releases/tag/v1.5.3

**Comment by notxt** [comment]
thanks @MikeRileyGTRI! 💖
